import type { Metadata } from "next";
// Bỏ qua tải font từ Google do lỗi mạng
// import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.scss";
import { cn } from "@/lib/utils";

// Components
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

const interVariable = "--font-sans";
const geistSansVariable = "--font-geist-sans";
const geistMonoVariable = "--font-geist-mono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSansVariable,
        geistMonoVariable,
        "font-sans",
        interVariable,
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Header />

        <main className="flex-1 z-0">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
