import type { Metadata } from "next";
import "./globals.scss";
import { cn } from "@/lib/utils";

const interVariable = "--font-sans";
const geistSansVariable = "--font-geist-sans";
const geistMonoVariable = "--font-geist-mono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSansVariable,
        geistMonoVariable,
        "font-sans",
        interVariable,
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <main className="flex-1 z-0">{children}</main>
      </body>
    </html>
  );
}
